apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  labels:
    app: n8n-deployment
spec:
  selector:
    app: n8n-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678